project:
  type: book
  output-dir: docs

book:
  title: "Machine Learning Intuition"
  author: "Eliott Kalfon"
  date: "1/04/2026"
  chapters:
    - text: "Epigraph"
      file: epigraph.qmd
    - index.qmd
    - part: "Introduction to Machine Learning"
      chapters:
      - intro.qmd
      - chapters/defining-prediction.qmd
      - chapters/types-ml.qmd
      - chapters/ai-ml-ds.qmd
      - chapters/data-space.qmd
      - chapters/distance.qmd
      - chapters/neighbours.qmd
    - part: "Model Evaluation"
      chapters: 
        - chapters/model-evaluation.qmd
        - chapters/evaluation-classification.qmd
        - chapters/evaluation-regression.qmd
    - part: "Decision Trees"
      chapters:
        - chapters/trees-intuition.qmd
        - chapters/splitting-maths.qmd
        - chapters/recursion.qmd
        - chapters/trees-proba-reg.qmd
    - part: "Data Preprocessing"
      chapters:
      - chapters/data-preprocessing.qmd
      - chapters/categorical-variables.qmd
      - chapters/datetime.qmd
      - chapters/missing-numerical-values.qmd
      - chapters/missing-categorical-values.qmd
      - chapters/scaling.qmd
    - part: "Bringing it all Together"
      chapters:
      - chapters/end-to-end.qmd
      - chapters/generative-ai.qmd
    - references.qmd
    - acknowledgments.qmd
  page-footer:
    left: "Copyright &copy; Eliott Kalfon 2025. All rights reserved."

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    number-sections: true
    exercise:
      solutions: true
    include-in-header: google-analytics.html
    include-after-body: 
     - cookie_banner.html
     - footer.html
  pdf:
    documentclass: book
    number-sections: true
    exercise:
      solutions: true
    classoption: 
      - oneside              
    geometry:
      - margin=1in
      - heightrounded        
  epub:
    toc: true
    number-sections: true
    code-line-numbers: false
    highlight-style: none
    code-block-bg: false
    code-block-border-left: false       
    css:
      - epub-base.css
      - epub-tables.css




